name: Electron App Build on Release

# Trigger the workflow when a new release is created
on:
  release:
    types:
      - published  # Trigger when a release is published

jobs:
  build:
    runs-on: macos-latest  # Using macOS to build the DMG file

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Using Node.js 18.x LTS

    - name: Install dependencies
      run: |
        npm ci

    - name: Build Electron App
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm run build  # Ensure 'electron-builder' is in your package.json scripts

    - name: Upload DMG to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        RELEASE_TAG="${{ github.event.release.tag_name }}"  # Get the release tag name
        gh release upload $RELEASE_TAG dist/*.dmg --clobber

    - name: Upload Artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v4  # Updated to the latest supported version
      with:
        name: electron-build
        path: dist/