name: Electron App Build

# Trigger workflow on push to the main branch or pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # You can also use 'ubuntu-latest' for Linux or 'windows-latest' for Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your Node.js version

    - name: Install dependencies
      run: |
        npm ci  # Install dependencies using the lockfile (or npm install)

    - name: Build Electron App
      run: |
        npm run build  # Run your build script (make sure it's defined in package.json)

    - name: Upload Artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: electron-build
        path: |
          dist/  # This assumes your build output is in the 'dist' folder. Adjust as needed